ApplyUni/Models/profiency.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profiency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profiency()
        {
            this.Language = new HashSet<Language>();
        }
    
        public int id { get; set; }
        public string profiency_level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Language> Language { get; set; }
    }
}

ApplyUni/Areas/Back/Controllers/profienciesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApplyUni.Models;
using ApplyUni.Filter;

namespace ApplyUni.Areas.Back.Controllers
{
    [Auth]
    public class profienciesController : Controller
    {

        private ApplyEntities3 db = new ApplyEntities3();

        // GET: Back/profiencies
        public ActionResult Index()
        {
            return View(db.profiency.ToList());
        }

        // GET: Back/profiencies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            profiency profiency = db.profiency.Find(id);
            if (profiency == null)
            {
                return HttpNotFound();
            }
            return View(profiency);
        }

        // GET: Back/profiencies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Back/profiencies/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,profiency_level")] profiency profiency)
        {
            if (ModelState.IsValid)
            {
                db.profiency.Add(profiency);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(profiency);
        }

        [Admlvl]
        // GET: Back/profiencies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            profiency profiency = db.profiency.Find(id);
            if (profiency == null)
            {
                return HttpNotFound();
            }
            return View(profiency);
        }

        [Admlvl]
        // POST: Back/profiencies/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,profiency_level")] profiency profiency)
        {
            if (ModelState.IsValid)
            {
                db.Entry(profiency).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(profiency);
        }
        [Admlvl]
        // GET: Back/profiencies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            profiency profiency = db.profiency.Find(id);
            if (profiency == null)
            {
                return HttpNotFound();
            }
            return View(profiency);
        }

        [Admlvl]
        // POST: Back/profiencies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            profiency profiency = db.profiency.Find(id);
            db.profiency.Remove(profiency);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ApplyUni/Areas/Back/Views/profiencies/Create.cshtml
@model ApplyUni.Models.profiency

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="margin-top:65px;">Create</h2>

@using (Html.BeginForm("Create", "profiencies", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>profiency</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.profiency_level,"Profiency level name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profiency_level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profiency_level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-gradient waves-light waves-effect w-md">Create</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ApplyUni/Areas/Back/Views/profiencies/Delete.cshtml
@model ApplyUni.Models.profiency

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="margin-top:60px;">Delete</h2>
<h3 style="color:#f36270;">Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal" style="margin-left: 20px;">
        <dt>
          Profiency level name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.profiency_level)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="submit" class="btn btn-danger waves-light waves-effect w-md">Delete</button> | |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ApplyUni/Areas/Back/Views/profiencies/Details.cshtml
@model ApplyUni.Models.profiency

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h4 style="margin-top: 65px;">Details</h4>

<div>
    <hr />
    <dl class="dl-horizontal" style="margin-left: 20px;">
        <dt>
            Profiency level name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.profiency_level)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ApplyUni/Areas/Back/Views/profiencies/Edit.cshtml
@model ApplyUni.Models.profiency

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="margin-top:65px;">Edit</h2>

@using (Html.BeginForm("Edit", "profiencies", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>profiency</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.profiency_level,"Profiency level name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profiency_level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profiency_level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-gradient waves-light waves-effect w-md">Save</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ApplyUni/Areas/Back/Views/profiencies/Index.cshtml
@model IEnumerable<ApplyUni.Models.profiency>

@{
    ViewBag.Title = "Profiency";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Profiency</h2>

<p>
    @Html.ActionLink("Create New", "Create", "profiencies", null, new { @class = "btn btn-gradient waves-light waves-effect w-md" })
</p>
<div class="card-box table-responsive">
    <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>
                   Profiency level name
                </th>
                <th></th>
            </tr>
        </thead>
        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.profiency_level)
                </td>
                <td>
                    <button class="btn-outline-** btn btn-light waves-effect w-md">
                        @Html.ActionLink("Edit", "Edit", new { id = item.id, @style = "color:black" })
                    </button>
                    <button class="btn-outline-** btn btn-light waves-effect w-md">
                        @Html.ActionLink("Details", "Details", new { id = item.id })
                    </button>
                    <button class="btn-outline-** btn btn-light waves-effect w-md">
                        @Html.ActionLink("Delete", "Delete", new { id = item.id })
                    </button>
                </td>
            </tr>
        }

    </table>
</div>