ApplyUni/Models/Faq.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faq
    {
        public int id { get; set; }
        public string name { get; set; }
        public string descripition { get; set; }
    }
}

ApplyUni/Areas/Back/Controllers/FaqsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApplyUni.Models;
using ApplyUni.Filter;

namespace ApplyUni.Areas.Back.Controllers
{
    [Auth]
    public class FaqsController : Controller
    {
        private ApplyEntities3 db = new ApplyEntities3();

        // GET: Back/Faqs
        public ActionResult Index()
        {
            return View(db.Faq.ToList());
        }

        // GET: Back/Faqs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faq faq = db.Faq.Find(id);
            if (faq == null)
            {
                return HttpNotFound();
            }
            return View(faq);
        }

        // GET: Back/Faqs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Back/Faqs/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,descripition")] Faq faq)
        {
            if (ModelState.IsValid)
            {
                db.Faq.Add(faq);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(faq);
        }

        [Admlvl]
        // GET: Back/Faqs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faq faq = db.Faq.Find(id);
            if (faq == null)
            {
                return HttpNotFound();
            }
            return View(faq);
        }
        [Admlvl]
        // POST: Back/Faqs/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,descripition")] Faq faq)
        {
            if (ModelState.IsValid)
            {
                db.Entry(faq).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(faq);
        }
        [Admlvl]
        // GET: Back/Faqs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faq faq = db.Faq.Find(id);
            if (faq == null)
            {
                return HttpNotFound();
            }
            return View(faq);
        }
        [Admlvl]
        // POST: Back/Faqs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Faq faq = db.Faq.Find(id);
            db.Faq.Remove(faq);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ApplyUni/Areas/Back/Views/Faqs/Create.cshtml
@model ApplyUni.Models.Faq

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

<h2 style="margin-top:65px;">Create</h2>

@using (Html.BeginForm("Create", "Faqs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Faq</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name,"Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripition,"Descripiton", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.descripition, 10, 100, new { @class = "ckeditor" })
                @Html.ValidationMessageFor(model => model.descripition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-gradient waves-light waves-effect w-md">Create</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ApplyUni/Areas/Back/Views/Faqs/Delete.cshtml
@model ApplyUni.Models.Faq

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="margin-top:60px;">Delete</h2>
<h3 style="color:#f36270;">Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal" style="margin-left: 20px;">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
          Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripition)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="submit" class="btn btn-danger waves-light waves-effect w-md">Delete</button> | |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ApplyUni/Areas/Back/Views/Faqs/Details.cshtml
@model ApplyUni.Models.Faq

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}


<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal" style="margin-left: 20px;">
        <dt>
           Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
           Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripition)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ApplyUni/Areas/Back/Views/Faqs/Edit.cshtml
@model ApplyUni.Models.Faq

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="margin-top:65px;">Edit</h2>

@using (Html.BeginForm("Edit", "Faqs", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Faq</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name,"Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripition, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.descripition, 10, 100, new { @class = "ckeditor" })
                @Html.ValidationMessageFor(model => model.descripition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-gradient waves-light waves-effect w-md">Save</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ApplyUni/Areas/Back/Views/Faqs/Index.cshtml
@model IEnumerable<ApplyUni.Models.Faq>

@{
    ViewBag.Title = "FAQ";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>FAQ</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Faqs", null, new { @class = "btn btn-gradient waves-light waves-effect w-md" })
</p>
<div class="card-box table-responsive">
    <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>
                   Name
                </th>
                <th>
                Description
                </th>
                <th></th>
            </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.Raw(item.descripition.Length > 200 ? item.descripition.Substring(0, 250) : item.descripition)...
                    </td>
                    <td>
                        <button class="btn-outline-** btn btn-light waves-effect w-md">
                            @Html.ActionLink("Edit", "Edit", new { id = item.id, @style = "color:black" })
                        </button>
                        <button class="btn-outline-** btn btn-light waves-effect w-md">
                            @Html.ActionLink("Details", "Details", new { id = item.id })
                        </button>
                        <button class="btn-outline-** btn btn-light waves-effect w-md">
                            @Html.ActionLink("Delete", "Delete", new { id = item.id })
                        </button>
                    </td>
                </tr>
            }

    </table>
    </div>