ApplyUni/Models/degree_level.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplyUni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class degree_level
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public degree_level()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int id { get; set; }
        public string level { get; set; }
        public Nullable<int> value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}

ApplyUni/Areas/Back/Controllers/degree_levelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApplyUni.Models;
using ApplyUni.Filter;

namespace ApplyUni.Areas.Back.Controllers
{
    [Auth]
    public class degree_levelController : Controller
    {
        private ApplyEntities3 db = new ApplyEntities3();

        // GET: Back/degree_level
        public ActionResult Index()
        {
            return View(db.degree_level.ToList());
        }

        // GET: Back/degree_level/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            degree_level degree_level = db.degree_level.Find(id);
            if (degree_level == null)
            {
                return HttpNotFound();
            }
            return View(degree_level);
        }

        // GET: Back/degree_level/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Back/degree_level/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,level,value")] degree_level degree_level)
        {
            if (ModelState.IsValid)
            {
                db.degree_level.Add(degree_level);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(degree_level);
        }

        [Admlvl]
        // GET: Back/degree_level/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            degree_level degree_level = db.degree_level.Find(id);
            if (degree_level == null)
            {
                return HttpNotFound();
            }
            return View(degree_level);
        }

        [Admlvl]
        // POST: Back/degree_level/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,level,value")] degree_level degree_level)
        {
            if (ModelState.IsValid)
            {
                db.Entry(degree_level).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(degree_level);
        }
        [Admlvl]
        // GET: Back/degree_level/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            degree_level degree_level = db.degree_level.Find(id);
            if (degree_level == null)
            {
                return HttpNotFound();
            }
            return View(degree_level);
        }
        [Admlvl]
        // POST: Back/degree_level/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            degree_level degree_level = db.degree_level.Find(id);
            db.degree_level.Remove(degree_level);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ApplyUni/Areas/Back/Views/degree_level/Create.cshtml
@model ApplyUni.Models.degree_level

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

<h2 style="margin-top:65px;">Create</h2>

@using (Html.BeginForm("Create", "degree_level", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>degree_level</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.level, "Study degree", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.value, "Degree point", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-gradient waves-light waves-effect w-md">Create</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ApplyUni/Areas/Back/Views/degree_level/Delete.cshtml
@model ApplyUni.Models.degree_level

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="margin-top:60px;">Delete</h2>
<h3 style="color:#f36270;">Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal" style="margin-left: 20px;">
        <dt>
           Study degree
        </dt>

        <dd>
            @Html.DisplayFor(model => model.level)
        </dd>

        <dt>
            Degree point
        </dt>

        <dd>
            @Html.DisplayFor(model => model.value)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="submit" class="btn btn-danger waves-light waves-effect w-md">Delete</button> | |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ApplyUni/Areas/Back/Views/degree_level/Details.cshtml
@model ApplyUni.Models.degree_level

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal" style="margin-left: 20px;">
        <dt>
          Study degree
        </dt>

        <dd>
            @Html.DisplayFor(model => model.level)
        </dd>

        <dt>
           Degree point
        </dt>

        <dd>
            @Html.DisplayFor(model => model.value)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ApplyUni/Areas/Back/Views/degree_level/Edit.cshtml
@model ApplyUni.Models.degree_level

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="margin-top:65px;">Edit</h2>

@using (Html.BeginForm("Edit", "degree_level", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>degree_level</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.level, "Study degree", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.value, " Degree point", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-gradient waves-light waves-effect w-md">Save</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ApplyUni/Areas/Back/Views/degree_level/Index.cshtml
@model IEnumerable<ApplyUni.Models.degree_level>

@{
    ViewBag.Title = "University degree";
    Layout = "~/Areas/Back/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>University degree</h2>

<p>
    @Html.ActionLink("Create New", "Create", "degree_level", null, new { @class = "btn btn-gradient waves-light waves-effect w-md" })
</p>
<div class="card-box table-responsive">
    <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>
                   Study degree
                </th>
                <th>
                    Degree point
                </th>
                <th></th>
            </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.level)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.value)
                    </td>
                    <td>
                        <button class="btn-outline-** btn btn-light waves-effect w-md">
                            @Html.ActionLink("Edit", "Edit", new { id = item.id, @style = "color:black" })
                        </button>
                        <button class="btn-outline-** btn btn-light waves-effect w-md">
                            @Html.ActionLink("Details", "Details", new { id = item.id })
                        </button>
                        <button class="btn-outline-** btn btn-light waves-effect w-md">
                            @Html.ActionLink("Delete", "Delete", new { id = item.id })
                        </button>
                    </td>
                </tr>
            }

    </table>
    </div>